-- SQL Schema for Supabase LeadPulse Database
-- Copy and run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create leads table
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id TEXT UNIQUE NOT NULL,
    name TEXT,
    query TEXT,
    is_spending_on_ads TEXT,
    reviews TEXT,
    rating TEXT,
    first_review TEXT,
    website TEXT,
    phone TEXT,
    can_claim TEXT,
    email TEXT,
    linkedin TEXT,
    twitter TEXT,
    facebook TEXT,
    youtube TEXT,
    instagram TEXT,
    owner_name TEXT,
    main_category TEXT,
    workday_timing TEXT,
    is_temporarily_closed TEXT,
    address TEXT,
    review_keywords TEXT,
    link TEXT,
    contacts_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create contacts table
CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_place_id TEXT REFERENCES public.leads(place_id) ON DELETE CASCADE,
    name TEXT,
    role TEXT,
    email TEXT,
    phone TEXT,
    linkedin TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create indexes for performance & deduplication
CREATE INDEX IF NOT EXISTS idx_leads_place_id ON public.leads(place_id);
CREATE INDEX IF NOT EXISTS idx_leads_name_address ON public.leads(name, address);
CREATE INDEX IF NOT EXISTS idx_contacts_lead_place_id ON public.contacts(lead_place_id);

-- 4. Enable Row Level Security (RLS) but allow public/anon access if using anon key
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to leads" ON public.leads FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to contacts" ON public.contacts FOR ALL USING (true) WITH CHECK (true);
